// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using UIKit;
using MvvmCTable.core;

namespace MvvmCTable.UI.iOS
{
	public partial class CollectionViewCell : MvxCollectionViewCell
	{
		internal static readonly NSString Identifier = new NSString("collectionCell");

		public CollectionViewCell (IntPtr handle) : base (handle)
		{

			CreateBindings();
			}


		public void setValueOnLabel()
		{
			// lbl_FirstName.Text = "vijay";
			//lbl_SecondName.Text = "yadav";
			//CreateBindings();
		}

		public void CreateBindings()
		{
			
			this.DelayBind(() =>
			{

				MvxFluentBindingDescriptionSet<CollectionViewCell, JackModel> set =
					this.CreateBindingSet<CollectionViewCell, JackModel>();

				set.Bind(lbl_FirstName).To(vm => vm.FirstName);
				set.Bind(lbl_SecondName).To(vm => vm.LastName);

				set.Apply();
			});
		}
	}
}
