// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using MvvmCTable.core;
using UIKit;

namespace MvvmCTable.UI.iOS
{
	[MvxFromStoryboard(StoryboardName = "Main")]
	public partial class DetailView : MvxViewController
	{
		public DetailView (IntPtr handle) : base (handle)
		{
		}

		public NewFarmPopView Vc; 
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			MvxFluentBindingDescriptionSet<DetailView,DetailViewModel > set =
			   this.CreateBindingSet<DetailView, DetailViewModel>();

			set.Bind(btn_NextView).To(vm => vm.ClickCommand);
			set.Bind(btn_ShowEvaluationView).To(vm => vm.ClickShowEvaluation);
			//Vc = this.Storyboard.InstantiateViewController("NewFarmPopView") as NewFarmPopView;

			//Vc = new NewFarmPopView();
			set.Apply();
		}


		partial void prs_Btn(NSObject sender)
		{
			Console.WriteLine("btn press for new farm");

			//NewFarmPopView Vc = new NewFarmPopView();
			//PresentViewController(Vc, true, null);
			//Vc.PresentModalViewController = UIModalPresentationStyle.FormSheet;

			try {
			
			Vc.ModalPresentationStyle = UIModalPresentationStyle.FormSheet;
				Vc.PreferredContentSize = new CoreGraphics.CGSize(500, 500);
				this.PresentViewController(Vc, true, null);
			
			}
			catch (Exception ex) {

				Console.WriteLine(ex.Message);
			}


		}
	}
}
