// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using MvvmCTable.core;
using UIKit;


namespace MvvmCTable.UI.iOS
{
	[MvxFromStoryboard(StoryboardName = "Main")]
	public partial class NewFarmPopView : MvxViewController<NewFarmPopViewModel>, IMvxModalIosView
	{
		public NewFarmPopView (IntPtr handle) : base (handle)
		{
			ModalPresentationStyle = UIModalPresentationStyle.FormSheet;

			this.PreferredContentSize = new CoreGraphics.CGSize(500, 500);
		}

		//public NewFarmPopView() : base("NewFarmPopView", null)
		//{
			
		//}


		//FarmPopTableSource _farmPopTableViewSource;
		//protected NewFarmPopViewModel NewFarmPopViewModel => ViewModel as NewFarmPopViewModel;

		public override void ViewDidLoad()
		{
			
			// _farmPopTableViewSource = new FarmPopTableSource(table_View);

			base.ViewDidLoad();

			MvxFluentBindingDescriptionSet<NewFarmPopView, NewFarmPopViewModel> set =
			   this.CreateBindingSet<NewFarmPopView, NewFarmPopViewModel>();

			//set.Bind(_farmPopTableViewSource).To(vm => vm._farmStaticValue);
			set.Bind(prs_Cancel).To(vm => vm.ClickCommand);

			set.Apply();

			//table_View.Source = _farmPopTableViewSource;
			//table_View.ReloadData();


		}

		//public override void ViewWillLayoutSubviews()
		//{
		//	base.ViewWillLayoutSubviews();
		//	this.View.Bounds = new CoreGraphics.CGRect(0.0, 0.0, 500, 300);
		//}
	}
}
