// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using UIKit;

namespace MvvmCTable.UI.iOS
{
	public partial class NewVisitView :MvxViewController, IMvxModalIosView
	{
		public NewVisitView (IntPtr handle) : base (handle)
		{
		}
	}
}
