// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using UIKit;
using MvvmCTable.core;
using MvvmCross.Binding.BindingContext;

namespace MvvmCTable.UI.iOS
{
	[MvxFromStoryboard(StoryboardName = "Main")]
	public partial class SearchResultView : MvxViewController<SearchResultViewModel>
	{
		public SearchResultView (IntPtr handle) : base (handle)
		{
		}

		SearchResultsTableViewSource _searchResultsTableViewSource;
		protected SearchResultViewModel SearchResultViewModel => ViewModel as SearchResultViewModel;



		public override void ViewDidLoad()
		{
			
			_searchResultsTableViewSource = new SearchResultsTableViewSource(table_View);

			base.ViewDidLoad();

			MvxFluentBindingDescriptionSet<SearchResultView, SearchResultViewModel> set =
			   this.CreateBindingSet<SearchResultView, SearchResultViewModel>();

			set.Bind(_searchResultsTableViewSource).To(vm => vm.Vijis);
			set.Bind(btn_Test).To(vm => vm.ClickCommand);
			set.Apply();

			table_View.Source = _searchResultsTableViewSource;
			table_View.ReloadData();


		}




	}
}
